### ISSUE TITLE
Review 2, F. Witherden

### ISSUE THREAD

**Issue by labarba** [barbagroup/cloud-repro#2] opened 2019-07-29 16:13 UTC
Citation

> Witherden, Freddie (2019): Review of Reproducible Workflow on a Public Cloud for Computational Fluid Dynamics. figshare. Online resource. https://doi.org/10.6084/m9.figshare.9159740.v1

Portions of the review report quoted here by permissions granted on the original under a CC-BY license.

**Comment by mesnardo** [comment] 2019-07-31 16:28
# Comment 1

* [x] Whilst the manuscript is well written the narrative is somewhat muddled. It starts with an overview of reproducible computational research, then pivots to how containers can be employed within the context of cloud computing, then jumping to benchmarks of one particular cloud providers' hardware, and then -- finally -- pivots a final time to a cost analysis of the public cloud for simulations. These are all interesting topics. Indeed, many a conference proceeding has been dedicated to each of these areas. However, by combining them into a single 10 page document this present manuscript fails to do justice to any of these areas. Further, the high degree of specificity will likely have a negative impact the relevance of the manuscript going forwards; a consequence of it being a review of the current state of affairs of a rapidly evolving field. It would therefore be better if it focused on just one or two areas such as "benchmarking cloud computing platforms" or "reproducibility through containers."

---

**Reply**

* The main goal of this manuscript is to report how to conduct CFD research in a reproducible way on a public cloud, laying out all the tools we used and the steps we undertook. We intend this paper to also serve as a mini-tutorial for researchers wanting to adopt these reproducible practices (we have observed when giving seminars or domain-conference talks that containers haven't disseminated to the CFD community). We use Docker containers to capture the computational environment and Microsoft Azure tools to capture the run-time environment. The degree of specificity is, in part, the point: precisely reproducing our work presumes deploying the same computational environment.
* Right now, researchers using scientific computing are still concerned about cost and performances on public clouds, and this is why we provide benchmark results and are report how much it costs to run our CFD application. Freniere et al. (2016) reported performance degradation on AWS (compared to their local cluster). But in the last three years, cloud providers have improved their offerings for HPC solutions. Thus, another objective is to update the record on the observations made by Freniere et al. (in the same journal) to the new cloud services introduced in the last two years.
* Although cloud computing is a rapidly evolving field, we believe it is important to report on the current state of public cloud offerings for academic applications. 
* The reviewer is a top expert in HPC, and we understand from this point of view it seems the paper does not do justice to the various topics covered. But the intended audience of this paper is not, in fact, either of our reviewers (their expertise was needed, of course, to provide a quality review of the manuscript!). The audience is intended to be researchers using scientific computing (possibly on old and over-subscribed university clusters), who are curious about using cloud resources, and interested in reproducible practices, but need guidelines to adopt these.
* Neither benchmarking cloud computing, nor reproducibility with containers, were a central focus for our paper. We include some benchmark results to update the record with respect to the article by Freniere et al., appearing in the same journal. We use container technology for our reproducible workflow (as others have), but extend the reproducibility ideas to automatic configuration of cloud resources.

**Changes**

* We made several changes, responding to both reviewers, which make the aims of the paper more clear. In particular, the Abstract and Introduction prepare the reader better for the rest of the paper.

**Comment by mesnardo** [comment] 2019-07-31 16:29
# Comment 2

* [x] The manuscript only appears to be concerned with reproducibility in the 'now' and pays no consideration to 'link rot' and if one will be able to build and run the proposed containers in 5, 10, or even 20 years. (C.f. Old F77 codes which are expected to remain viable long after the heat death of the universe.) This is one of the most serious issues affecting reproducible research today. 
* [x] Further, the manuscript also glosses over several of the issues regarding deploying containerised applications within an HPC context. One of the most important is with regards to MPI libraries and the fact that many HPC/Cloud environments depend on specific MPI library. For example, Cray machines require Cray MPI, IBM POWER 9 machines require Spectrum MPI, and so on. This results in a 'leaky abstraction' for the container must now concern itself with the idiosyncrasies of the hardware which it is running on.

---

**Reply**
* Obsolescence of digital research objects, including software libraries and computational environments, is an acknowledged source of non-reproducibility, in the long run. The recent report of the National Academies highlights it so [page?]. Indeed, tools in our workflow that we have no control over (Azure CLI, Batch Shipyard) will likely change, and perhaps not be backwards compatible. That is inevitable. But when they do, our fully documented workflow (via human-readable configuration files) will continue to offer transparency of what we did and how we did it. 
* "issues regarding deploying containerised applications within an HPC context" — Broad portability of our software and workflow is not our objective, and would (arguably) not be justified. Our software is currently only used in research projects within our lab: what reasons would call for the highly skilled and labor intensive software engineering required to deliver broadly portable software and workflow?The goal is, rather, to publish our computational research with deep transparency. The Docker images built for this study were specifically crafted to run on Microsoft Azure with Azure Batch service on RDMA-capable nodes with Linux-based virtual machines. Readers interested in reproducing our analysis should do it under the same conditions, which include the same cloud environment. We have added text in the introduction explaining the limitations of this work with respect to portability issues.

**Changes**

* Added language about limitations regarding portability issues (97e0512).
* Re-arrange last paragraph of the conclusion to emphasize the limitation of the reproducibility, and add citation to the new NASEM report (6f029e9).

**Comment by mesnardo** [comment] 2019-07-31 16:32
# Comment 3

As highlighted by the authors' in both the manuscript and the Dockerfiles it is necessary (on the Azure platform at least) to use the Intel MPI library. This is highly problematic.

* [x] (a) It explicitly ties the container to x86 based clusters which support the Intel MPI library (even when the underlying solver software and libraries are portable).
* [x] (b) The library itself has to be downloaded off a random URL on the Intel website (whose long term stability and availability is suspect).
* [x] (c) Downloading the library requires acceptance of a proprietary EULA whose terms could easily put an unsuspecting researcher who does not also possess a JD into serious legal trouble with the Intel Corporation -- especially when it comes to moving the container between systems which may be employed for commercial gain. (Aside: whilst in all of the Dockerfiles an rm -rf is performed at the end to remove the Intel components, due to the layered nature of Docker images the compilers are *100%* still present in the resulting images and thus may result in even more legal issues for an unsuspecting researcher.)
* [x] (d) It is also sub-optimal in the context of CUDA applications for the Intel MPI library is not (to the reviewers' knowledge) CUDA aware and thus parallel CUDA applications are likely to run substantially slower than on say OpenMPI or MVAPICH2 w/GDR.

The result is a highly fragile system which is coupled to the wonts of one particular cloud platform.

Similarly, with the CUDA containers there are also compatibility issues.  The most obvious is the container specifying a specific GPU architecture version which may not map onto the hardware of the host.  This is another 'leaky abstraction' issue.

---

**Reply**

* (a) As indicated in our reply to Comment 2, portability to other hardware is not our goal. We do, in fact, tie the reproducibility of our results to using the exact same computational environment.
* (b) We downloaded the MPI library from the Intel website just to build the Docker images locally. These images are now published on DockerHub and publicly available. Readers interested in reproducing our analysis under the same conditions (on Azure) do not need to dowload the Intel MPI library.
* (c) The Intel MPI library is under [Intel Simplified Software License](https://software.intel.com/en-us/license/intel-simplified-software-license), which allows for redistribution as long as the copyright note remains. On downloading the library, the LICENSE file is included with the source. There is no mention of commercial uses in the license, so they are not disallowed. Note that we are not using Intel compilers, just the MPI library. For greater transparency, we added a note in the README under the `docker` sub-folder saying the user who downloads the Docker image agrees to the Intel license terms. The same note was also added to the description of the Docker images on DockerHub.
* (d) We _need_ to use Intel MPI library, because the Azure nodes we are using require it. Our software is, indeed, using GPU computing with CUDA. Other MPI libraries may be more performant with CUDA,  but they are not available in the RDMA-capable Azure nodes used. Note that performance is not our highest priority, reproducibility is.

**Changes**

* Add note about Intel Simplified Software License (d3c8543).

**Comment by mesnardo** [comment] 2019-07-31 16:35
# Comment 4

* [x] Table 1 contains performance data for the Azure cloud nodes and the Colonial One nodes. However, it makes no mention of the memory configuration of the nodes (# of channels and speed rating of the DDR memory). Different configurations here can result in substantial differences with regards to peak memory bandwidth. This is vital as all of the benchmarks fall into the category of 'memory bandwidth bound problems'. Along these lines it is also important to note if ECC was enabled or disabled for the NVIDIA GPUs as this can have a substantial impact on performance.

---

**Reply**

* We agree with the comments made by the reviewer. The memory configuration on Colonial One is 128GB of 1600MHz DDR3 ECC Register DRAM for `ivygpu` nodes and 128GB of 1866MHz DDR3 ECC Registered DRAM for `short` nodes. However, we do not have such information for Azure. We contacted Microsoft Azure about that and they told us there is no publicly released information regarding the speed and channels. Right now, only CPU information are publicly available (already included in Table 1 of the manuscript).
* All runs using GPU computing that are reported in the manuscript were done with ECC enabled for NVIDIA GPUs (on Azure and on Colonial One). As suggested by the reviewer, we added that information to the manuscript (in the caption of Table 1).

**Changes**

* Mention ECC was enabled for GPU computing in caption of Table 1 (5ad8d81).

**Comment by mesnardo** [comment] 2019-07-31 16:36
# Comment 5

* [x] With regards to the benchmarks in Fig 2. could the authors explain why the lower latency for the Colonial One cluster at small message sizes does not translate into greater peak bandwidth at these sizes?

---

**Reply**
* We cannot explain that, because we don't know. We did, however, rerun the benchmarks on Colonial One, this time using Intel MPI (previous results used OpenMPI), and the results do get closer to those on Azure. In any case, the age of the system, the details of the hardware, or system software—we don't worry about the details, because the purpose of this figure is to update the reader on similar reports presented 3 years ago by Freniere et al.

**Changes**

* Update Figures 2 and 3 after re-running the benchmarks (MPI and Poisson) on Colonial One with the Intel MPI library; OpenMPI was used in the previous version of the manuscript (38dd7d0).

**Comment by mesnardo** [comment] 2019-07-31 16:37
# Comment 6

* [x] Fig 3 is somewhat cluttered and amounts to three plots in one. The first appears to be strong scaling on CPUs whilst the second two correspond to weak scaling on GPUs (although it is not elucidated as such). This breakdown seems somewhat arbitrary.

---

**Reply**
* We added parenthetical remarks to the text and restructured the caption, emphasizing the type of scaling shown in each plot (strong, weak). We still like the three panels in one figure, rather than breaking it into three figures: they all deal with the Poisson benchmark on the local cluster and the cloud. It seems like a matter of preference on how to present the data, but it is clear what each plot is presenting.

**Changes**

* Mention "strong scaling" for CPUs and "weak scaling" for GPUs to the text (38dd7d0).
* Restructure the caption text (a53ae04).

**Comment by mesnardo** [comment] 2019-07-31 16:37
# Comment 7

* [x] On line 45 of page 6 a remark is made around "One of the requirements for reproducible computational results is to make code available under a public license (allowing reuse and modification by others)." However this does not appear to follow; a piece of work whose code and data is made available for "reproducibility purposes only" would still appear to meet the requirements for facilitating reproducible computational results laid out in the introduction even though the license does not permit reuse or modification.

---

**Reply**

* Strictly speaking, the reviewer is correct. One _could_ make code available under a restrictive license that allows others to _only_ use it without modification to reproduce the results. That is certainly possible, but not good form, in our opinion. We added the word "ideally" in the parenthetical note, to be strictly accurate.

**Changes**

* Add word "ideally" in the parenthetical note (56028ea).

**Comment by mesnardo** [comment] 2019-07-31 16:38
# Comment 8

* [x] With regards to the CFD results there does not appear to be any kind of mesh/convergence study nor are any attempts made to quantify the uncertainties on the resulting C_L and C_D coefficients. As such it is difficult to know what to make of the results beyond "they look nice." Although the reviewer appreciates the focus of this paper is not the CFD results per-se it is nevertheless important when presenting numerical results to make a case that the method is resolving all relevant dynamics and that any time-averaged statistics are indeed converged.

---

**Reply**

* We do have results of a simulation with a mesh of doubled density in the near-body region, with the same stretching ratio moving away from it. It results in more than 230 million cells. The relative difference in time-averaged force coefficients was 6.5% for drag and 3% for lift. But the cost is about 7.4 times compared with the coarser-grid run shown in the paper. The purpose of this paper is not targeting the physics, but the reviewer is right to ask about the fidelity of the simulation shown, and other readers may have the same question. Therefore, we have added a passage at the end of section 3.3.2 with this very explanation, and added to the GitHub repository for this paper a Jupyter notebook with a comparison of the time-varying force coefficients between the coarser and finer meshes. The paper points to this notebook as supplementary material.

**Changes**

* Add a Jupyter Notebook with comparison of the force coefficients between the coarse and fine grids (c1ed36e).
* Add sentences about the run on the finer grid (201ef06).

**Comment by mesnardo** [comment] 2019-07-31 16:39
# Comment 9

* [x] Although the cost analysis is interesting without any real basis of comparison it is difficult to glean much from it.

---

**Reply**

* We used the the cloud platform Microsoft Azure because we received a sponsorship from the program "Microsoft Azure for Research." We have not tried other cloud providers. We do not report any cost analysis for local HPC cluster as the University is not willing to disclose information related to the cost of operating the cluster.

**Changes**

* No changes needed.

**Closed as completed** 2020-05-05 19:51 UTC
Labels: CiSE revision
